### ISSUE TITLE
Question: Where is Runelite.exe or .jar?

### ISSUE THREAD

**Issue by Acans** [USA-RedDragon/jagex-launcher-linux-flatpak#106]
I'm sorry for the newbie question, but I'm wondering if the RuneLite.exe or .jar file is located after being installed.

I have a Jagex account with linked characters but also a legacy account that isn't connected so whenever I want to play that, I want to just open Runelite so I can legacy login.

I enabled the hidden folders and found a .RuneLite folder in /home/.var/app/com.jagex.Launcher/ but didn't find a .exe or jar.

I also found a ThirdParty folder in /home/.local/share/flatpak/etc etc/com.jagex.Laucnher/ThirdParty however that folder is empty.

I don't think there's a bug as I followed the guide, and I can login and play with accounts via the Jagex account so maybe that ThirdParty folder is meant to be empty.

**Comment by USA-RedDragon** [comment]
Hello, sorry for the delay, I've been at a concert this weekend.

So essentially that `ThirdParty` directory gets "automagically" mounted by Flatpak at runtime if there are any of the `ThirdParty` packages installed (RuneLite or HDOS). Since that's only done at runtime, the RuneLite files you're looking for are usually under a directory like `~/.local/share/flatpak/runtime/com.jagex.Launcher.ThirdParty.RuneLite/x86_64/stable/active/files`

I don't really have a way to launch just RuneLite in the Flatpak since it's intended for the Jagex Launcher, but if you want to run it outside the Flatpak with the files it provides, something like this should work:

```bash
~/.local/share/flatpak/runtime/com.jagex.Launcher.ThirdParty.RuneLite/x86_64/stable/active/files/jre/bin/java -jar ~/.local/share/flatpak/runtime/com.jagex.Launcher.ThirdParty.RuneLite/x86_64/stable/active/files/RuneLite.jar
```
